### ISSUE TITLE
Include tags (via --decorate)

### ISSUE THREAD

**Issue by phhu** [codevey/parse-git-numstat#2]
It might be useful to include tags and branch info, produced with command ```git log --numstat --decorate```

Something like this:

```
//line 12 of index.js
  while (cursor.hasNext() && cursor.peek().length > 0) {
    const {sha,decoration} = matchGroups(/commit\s(?<sha>[a-zA-Z0-9]*)\s?(?<decoration>.*)?/, cursor.next());
    const tags = decoration && (decoration.match(/(?<=tag: ).*?(?=[,\)])/g) || undefined);
    const branch = decoration && (decoration.replace(/\((?:HEAD -> )?(.*?)(, )?(tag:.*)?\)/,"$1") || undefined);
    
    if (!sha) {
      throw new Error(`Could not parse git log entry with no sha given at line ${cursor.index()}`);
    }
```
and
```
//line 47 of index.js
    parsedLog.push({
      sha, decoration, tags, branch,
      author: matchGroups(/Author:\s(?<name>.*?)\s<(?<email>.*?)>/, author),
      merge,
      date,
      message,
      stat,
    });
```

**Comment by saintedlama** [comment]
Thanks for suggesting that feature. Implemented in version 1.1.0

**Comment by saintedlama** [comment]
@phhu is the feature working for you?

**Comment by phhu** [comment]
Thanks, tags and branches are working in 1.1.0.

(Also might be useful to have e.g. parent commit hash(es), format option %P.... though this would require a custom --format switch for git log, something like ```git log -2 --pretty="format:%C(yellow)commit %H%d%n%C(white)Parents: %P%nAuthor: %an <%ae>%nDate:   %ad%n%n%w(0,4,4)%B"``` )
